### PR TITLE
Add support for Blynclight Plus

### PR DESCRIPTION
**Pull request by andresol**
Added support for e.g Blynclight Plus or other Blynclight products.

### CODE REVIEW

**Comment by jedcn** [comment]
Hey there. Hope you're doing well.

What happened here?

Did you get this running locally?

Why would you close it?

**Comment by andresol** [comment]
It work very well, but I changed other things too after I created the pull req. This changes will break your code so I just closed it.

**Comment by jedcn** [comment]
Ok, well, I'm not really using this anymore so I'm open to talking about breaking changes.

If you want your changes just for yourself-- you can probably fork this project and keep it locally and be all good.

If you want to publish your changes (up to npmjs.com) because other people will use them we could do that under a new major version. I suspect you'd need some new documentation if you wanted people to understand what was up.

Either way-- I hope this was helpful to you for getting stuff going w/ whatever project you're thinking of and I hope you have a good day.

Best,

**Comment by andresol** [comment]
I'm just experimenting with Blynclight Plus so for now I just fork the project and keep it locally, but if it works very well I will contact you. Thanks! Your project has been very use full too me.

**Pull request closed without merging**
